/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.KhachHang;

import BUS.bus_Khachhang;
import DTO.dto_KhachHang;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author ThinkPro
 */
public class FormCapNhatKH extends JFrame {

    /**
     * Creates new form FormCapNhat
     */
    UI_KhachHang khachhangUI = new UI_KhachHang();
    bus_Khachhang busKH = new bus_Khachhang();
    static dto_KhachHang dtoKH = new dto_KhachHang();
    static int maKH;
    static Date date;
    ArrayList<String> dsChungChi;

    public FormCapNhatKH() {

        super();
        initComponents();
        showDSChungChi();
        txtCNTenKH.setText(dtoKH.getHoTen());
        txtCNSdt.setText(dtoKH.getSdt());
        txt_CNDiaChi.setText(dtoKH.getDiaChi());
        txt_CNDiem.setText(dtoKH.getDiemDauVao());
        cbGioiTinhKH.setSelectedItem(dtoKH.getGioiTinh());
        dateCapNhatKH.setDate(date);
        cbChungChi.setSelectedItem(dtoKH.getChungChi());
    }

    void showDSChungChi() {
        dsChungChi = busKH.layDS_ChungChi();
        if (dsChungChi != null) {
            for (int i = 0; i < dsChungChi.size(); i++) {
                cbChungChi.addItem(dsChungChi.get(i));
            }
        }
    }

    public void setDefaultInformations(dto_KhachHang dtoKH) {
        if (dtoKH != null) {
            this.dtoKH = dtoKH;
            maKH = dtoKH.getMaKH();
            System.out.println(dtoKH.getNgaySinh().substring(0, 10));
            try {
                date = new SimpleDateFormat("yyyy-MM-dd").parse(dtoKH.getNgaySinh().substring(0, 10));
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }

    public void thongTinChiTiet(dto_KhachHang dtoKH) {
        new FormCapNhatKH().setVisible(true);
        System.out.println(dtoKH.getHoTen());
        System.out.println(maKH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnCapNhatKH = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCNTenKH = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cbGioiTinhKH = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtCNSdt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_CNDiaChi = new javax.swing.JTextField();
        btnXacNhanCapNhat = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        dateCapNhatKH = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_CNDiem = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cbChungChi = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cập Nhật Khách Hàng");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        pnCapNhatKH.setBackground(new java.awt.Color(255, 255, 255));
        pnCapNhatKH.setPreferredSize(new java.awt.Dimension(520, 340));

        jLabel1.setText("HỌ VÀ TÊN");

        jLabel11.setText("GIỚI TÍNH");

        cbGioiTinhKH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));
        cbGioiTinhKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbGioiTinhKHActionPerformed(evt);
            }
        });

        jLabel9.setText("SỐ ĐIỆN THOẠI");

        jLabel10.setText("ĐỊA CHỈ");

        btnXacNhanCapNhat.setBackground(new java.awt.Color(91, 155, 213));
        btnXacNhanCapNhat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnXacNhanCapNhat.setForeground(new java.awt.Color(255, 255, 255));
        btnXacNhanCapNhat.setText("XÁC NHẬN");
        btnXacNhanCapNhat.setContentAreaFilled(false);
        btnXacNhanCapNhat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnXacNhanCapNhat.setFocusable(false);
        btnXacNhanCapNhat.setOpaque(true);
        btnXacNhanCapNhat.setPreferredSize(new java.awt.Dimension(209, 40));
        btnXacNhanCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanCapNhatActionPerformed(evt);
            }
        });

        jLabel6.setText("NGÀY SINH");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("CẬP NHẬT");

        jLabel12.setText("CHỨNG CHỈ");

        jLabel13.setText("ĐIỂM ĐẦU VÀO");

        javax.swing.GroupLayout pnCapNhatKHLayout = new javax.swing.GroupLayout(pnCapNhatKH);
        pnCapNhatKH.setLayout(pnCapNhatKHLayout);
        pnCapNhatKHLayout.setHorizontalGroup(
            pnCapNhatKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCapNhatKHLayout.createSequentialGroup()
                .addGroup(pnCapNhatKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnCapNhatKHLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(pnCapNhatKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnCapNhatKHLayout.createSequentialGroup()
                                .addGroup(pnCapNhatKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
                                .addGap(41, 41, 41)
                                .addGroup(pnCapNhatKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCNTenKH, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                                    .addComponent(cbGioiTinhKH, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dateCapNhatKH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(pnCapNhatKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnCapNhatKHLayout.createSequentialGroup()
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtCNSdt))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnCapNhatKHLayout.createSequentialGroup()
                                    .addGroup(pnCapNhatKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(pnCapNhatKHLayout.createSequentialGroup()
                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 14, Short.MAX_VALUE))
                                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(pnCapNhatKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txt_CNDiem, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txt_CNDiaChi, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                                        .addComponent(btnXacNhanCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cbChungChi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                    .addGroup(pnCapNhatKHLayout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(jLabel2)))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        pnCapNhatKHLayout.setVerticalGroup(
            pnCapNhatKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCapNhatKHLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(pnCapNhatKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCNTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnCapNhatKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dateCapNhatKH, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnCapNhatKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbGioiTinhKH, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnCapNhatKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCNSdt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnCapNhatKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_CNDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnCapNhatKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_CNDiem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnCapNhatKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbChungChi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnXacNhanCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnCapNhatKH, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnCapNhatKH, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(489, 475));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cbGioiTinhKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbGioiTinhKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbGioiTinhKHActionPerformed

    private void btnXacNhanCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanCapNhatActionPerformed
        String TenKH = txtCNTenKH.getText();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        String NgaySinh = "";
        if (dateCapNhatKH.getDate() == null) {
            System.out.println("Nhap ngay thang di cu");
        } else {
            NgaySinh = sdf.format(dateCapNhatKH.getDate());
        }
        int GioiTinh = cbGioiTinhKH.getSelectedIndex();
        String Sdt = txtCNSdt.getText();
        String Diem = txt_CNDiem.getText();
        String DiaChi = txt_CNDiaChi.getText();
        String cbCC = (String) cbChungChi.getSelectedItem();
        int ChungChi;
        if (cbCC.equals("IELTS")) {
            System.out.println("chay vao chung chi");
            ChungChi = 90;
            System.out.println(ChungChi);
        } else if (cbCC.equals("TOEIC LR")) {
            ChungChi = 91;
        } else if (cbCC.equals("CAMBRIDGE")) {
            ChungChi = 92;
        } else {
            ChungChi = 93;
        }
        if (TenKH.equals("") || NgaySinh.equals("") || Sdt.equals("") || Diem.equals("") || DiaChi.equals("")) {
            JOptionPane.showMessageDialog(null, "Bạn cần nhập đủ thông tin");
        } else {
            boolean kt = busKH.capnhatKH(new dto_KhachHang(maKH, TenKH, NgaySinh, GioiTinh, DiaChi, Sdt, Diem, ChungChi));
            if (kt == true) {
                JOptionPane.showMessageDialog(null, "Cập thành công");
                this.dispose();
                khachhangUI.showTable();
            } else {
                JOptionPane.showMessageDialog(null, "WRONG");
            }
        }
    }//GEN-LAST:event_btnXacNhanCapNhatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCapNhatKH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCapNhatKH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCapNhatKH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCapNhatKH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCapNhatKH().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnXacNhanCapNhat;
    private javax.swing.JComboBox<String> cbChungChi;
    private javax.swing.JComboBox<String> cbGioiTinhKH;
    private com.toedter.calendar.JDateChooser dateCapNhatKH;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel pnCapNhatKH;
    private javax.swing.JTextField txtCNSdt;
    private javax.swing.JTextField txtCNTenKH;
    private javax.swing.JTextField txt_CNDiaChi;
    private javax.swing.JTextField txt_CNDiem;
    // End of variables declaration//GEN-END:variables
}
